products:
  - "+00_04"

max_flex_rc: 10
max_flex_re: 15

solver:
  name: gurobi

bid_price_rc_data:
  1: 5.0
  2: 8.0

bid_price_re_data:
  1: 50.0
  2: 100.0
  3: 50.0
  4: 100.0

forecast:
  window_days: 30
  alpha_method: mean
